test:
#  asset_port:  80
  tags:        ON
  captcha:     ON
  acls:        ON
  grid:        ON
  fs_skin:     OFF
  sphinx:      OFF
  worker:      OFF
  uv:          OFF
  spreadsheet: ON


development:
#  asset_port: 7999
  mongrel:   OFF
  passenger: ON
  uv:
    switch:  ON
    activate_if:
      gem: 'uv'
  pdf:
    switch: ON
    engine: prince

  math:
    switch: ON
    live:   ON

  spreadsheet:
    switch:  ON
    activate_if:
      gem: 'simple_xlsx'

  tags:     ON
  captcha:  ON
  grid:     ON
  acls:     ON
  fs_skin:  ON
  sphinx:
    switch: OFF
    activate_if:
      gem: 'thinking_sphinx'
      adapter: 'mysql,postgresql'
    run_if:
      file: 'log/searchd.development.pid'
  worker:
    switch:  OFF
    activate_if:
      gem: 'delayed_job'

production:
# Port used only to provide assets during custom rendering (pdf).
# We need this to avoid deadlocks with round-robin based serving.
#  asset_port: 7999
  cache_path: '/public/cache'
  mongrel:   OFF
  passenger: ON
  uv:
    switch:  ON
    activate_if:
      gem: 'uv'
  spreadsheet:
    switch:  ON
    activate_if:
      gem: 'simple_xlsx'
  pdf:
    switch: ON
    engine: prince
  math:
    switch: ON
    live:   ON
  tags:     ON
  captcha:  ON
  grid:     ON
  acls:     ON
  fs_skin:  ON
  single:   OFF
  sphinx:
    switch: OFF
    activate_if:
      gem: 'thinking_sphinx'
      adapter: 'mysql,postgresql'
    run_if:
      file: 'log/searchd.pid'
  worker:
    switch:  OFF
    activate_if:
      gem: 'delayed_job'
