test:
#  asset_port:  80
  tags:        ON
  captcha:     ON
  acls:        ON
  grid:        ON
  fs_skin:     OFF
  sphinx:      OFF
  worker:      OFF
  uv:          OFF
  spreadsheet: ON
  activity:    ON
  currency:
    switch: ON
    app_id: test_app_id_xxx # APP_ID for testing is in config/currency_app_id.txt

development:
#  asset_port: 7999    
  cache_path: '/public'
  activity:  ON
  mongrel:   OFF
  passenger: ON
  uv:
    switch:  ON
    activate_if:
      gem: 'uv'
  pdf:
    switch: ON
    engine: wkhtmltopdf
    cmd: /usr/local/bin/wkhtmltopdf

  math:
    switch: ON
    live:   ON

  spreadsheet:
    switch:  ON
    activate_if:
      gem: 'simple_xlsx'

  tags:     ON
  captcha:  ON
  grid:     ON
  acls:     ON
  fs_skin:  ON
  sphinx:
    switch: OFF
    activate_if:
      gem: 'thinking_sphinx'
      adapter: 'mysql,postgresql'
    run_if:
      file: 'log/searchd.development.pid'
  worker:
    switch:  OFF
    activate_if:
      gem: 'delayed_job'

production:
# Port used only to provide assets during custom rendering (pdf).
# We need this to avoid deadlocks with round-robin based serving.
# Do not use with Passenger.
#  asset_port: 7999
#
# When external rendering engines (pdf) cannot get non-public assets, add the server ip to
# what Zena considers 'local'
#  local_ips: 123.45.67.89, 127.0.0.1
# index_on_fullpath: ON
  activity:  ON
  cache_path: '/public'
  mongrel:   OFF
  passenger: ON
  uv:
    switch:  ON
    activate_if:
      gem: 'uv'
  spreadsheet:
    switch:  ON
    activate_if:
      gem: 'simple_xlsx'
  pdf:
    switch: ON
    engine: wkhtmltopdf
    cmd: /usr/local/bin/wkhtmltopdf
  math:
    switch: ON
    live:   ON
  tags:     ON
  captcha:  ON
  grid:     ON
  acls:     ON
  fs_skin:  ON
  single:   OFF
  sphinx:
    switch: OFF
    activate_if:
      gem: 'thinking_sphinx'
      adapter: 'mysql,postgresql'
    run_if:
      file: 'log/searchd.pid'
  worker:
    switch:  OFF
    activate_if:
      gem: 'delayed_job'
