# Enter database configuration information here (rename this file "database.yml").
# You do not need to do any of this if you use capistrano (see config/deploy.rg).
# MySQL
login: &dev_login
  adapter: mysql
  socket: /tmp/mysql.sock
  username: root
  password:

development:
  database: zena_dev
  encoding: utf8
  <<: *dev_login

test:
  database: zena_test
  encoding: utf8
  <<: *dev_login


production:
  adapter: mysql
  socket: /tmp/mysql.sock
  database: zena_dev
  encoding: utf8
  username: root
  password:
