hpricot:
gettext:        '= 2.1.0'
ruby-recaptcha: '= 1.0.3'
syntax:         '= 1.0.0'
tzinfo:
uuidtools:      '= 2.0.0'
rails:          '= 2.3.11'
json:           '= 1.5.1'
authlogic:      '= 2.1.3'
fast_gettext:   '~> 0.4.16'
will_paginate:  '~> 2.3.12'
differ:         '= 0.1.2'
shoulda:        '= 2.10.3'
httparty:       '= 0.7.8'
open4:
daemons:        # upload progress
gem_plugin:     # upload progress
simple_xlsx_writer:    # spreadsheet
  lib:          'simple_xlsx'

querybuilder:   '= 1.1.4'
yamltest:       '= 0.7.0'
rubyless:       '= 0.8.8'
property:       '= 2.3.2'
versions:       '= 0.3.1'

jeweler:

RedCloth:
  lib:          'redcloth'
  version:      '= 3.0.4'

# ultraviolet needs oniguruma, which needs headers to compile
# ultraviolet:

# Cannot do "gem 'rmagick', '= 1.3.14'" on some hosts. Leave this alone and
# let 'require' pick whatever it can.
# rmagick:
#   optional:     yes
#   lib:          'RMagick'
#   version:      '= 2.13.1'

thinking-sphinx:
  optional:     yes
  brick:        sphinx
  lib:          'thinking_sphinx'
  version:      '= 1.3.14'

# needs riddle 1.0.10

ts-delayed-delta:
  optional:     yes
  brick:        sphinx
  lib:          'thinking_sphinx/deltas/delayed_delta'
  version:      '= 1.0.2'

delayed_job:
  optional:     yes
  brick:        worker
  # 2.0.3 does not work.
  # TODO: fix.
  version:      '= 1.8.4'
