hpricot:
gettext:        '= 2.1.0'
ruby-recaptcha: '= 1.0.3'
syntax:         '= 1.0.0'
tzinfo:         '= 0.3.26'
uuidtools:      '= 2.0.0'
rails:          '= 2.3.11'
json:           '= 1.5.1'
authlogic:      '= 2.1.3'
fast_gettext:   '~> 0.4.16'
will_paginate:  '~> 2.3.12'
differ:         '= 0.1.2'
shoulda:        '= 2.10.3'
httparty:       '= 0.7.8'

querybuilder:   '= 1.0.1'
yamltest:       '= 0.7.0'
rubyless:       '= 0.8.5'
property:       '= 2.2.0'
versions:       '= 0.3.1'
zafu:           '= 0.8.0'

jeweler:

RedCloth:
  lib:          'redcloth'
  version:      '= 3.0.4'

rmagick:
  optional:     yes
  lib:          'RMagick'
  version:      '= 2.13.1'

thinking-sphinx:
  optional:     yes
  brick:        sphinx
  lib:          'thinking_sphinx'
  version:      '= 1.3.14'

# needs riddle 1.0.10

ts-delayed-delta:
  optional:     yes
  brick:        sphinx
  lib:          'thinking_sphinx/deltas/delayed_delta'
  version:      '= 1.0.2'

delayed_job:
  optional:     yes
  brick:        worker
  # 2.0.3 does not work.
  # TODO: fix.
  version:      '= 1.8.4'
